CREATE TABLE [dbo].[Anstalld] (
    [Id]                       VARCHAR (8)   NOT NULL,
    [PersonNr]                 VARCHAR (20)  NULL,
    [PersonNummer]             VARCHAR (20)  NULL,
    [Name]                     VARCHAR (40)  NULL,
    [SortName]                 VARCHAR (8)   NULL,
    [Street]                   VARCHAR (40)  NULL,
    [Box]                      VARCHAR (40)  NULL,
    [Zip]                      VARCHAR (6)   NULL,
    [City]                     VARCHAR (40)  NULL,
    [Tel]                      VARCHAR (20)  NULL,
    [Tel2]                     VARCHAR (20)  NULL,
    [AnstDat]                  DATETIME      NULL,
    [AvgangsDatum]             VARCHAR (10)  NULL,
    [UtbetSatt]                SMALLINT      NULL,
    [BankKonto]                VARCHAR (20)  NULL,
    [ManadsLon]                MONEY         NULL,
    [TimLon]                   MONEY         NULL,
    [BilForman]                MONEY         NULL,
    [SemesterLonDay]           MONEY         NULL,
    [KvarSkattRest]            MONEY         NULL,
    [Kategori]                 SMALLINT      NULL,
    [UtbetIntervall]           SMALLINT      NULL,
    [SkattTabell]              FLOAT (53)    NULL,
    [Kst]                      VARCHAR (6)   NULL,
    [Kb]                       VARCHAR (6)   NULL,
    [Pt]                       VARCHAR (16)  NULL,
    [Remarks]                  VARCHAR (MAX) NULL,
    [SemesterDgr]              FLOAT (53)    NULL,
    [SemKvarBet]               FLOAT (53)    NULL,
    [SemKvarObet]              FLOAT (53)    NULL,
    [SemKvarSpar]              FLOAT (53)    NULL,
    [SemKvarForskott]          FLOAT (53)    NULL,
    [SemDgrUttagna]            FLOAT (53)    NULL,
    [SemDgrSkuld]              FLOAT (53)    NULL,
    [ArbetsTidVecka]           FLOAT (53)    NULL,
    [SkatteBer]                BIT           NULL,
    [EjJamkning]               BIT           NULL,
    [JamkningKr]               BIT           NULL,
    [JamkningProc]             BIT           NULL,
    [SidoInkomst]              BIT           NULL,
    [JamkningBelopp]           MONEY         NULL,
    [JamkningProcentSats]      FLOAT (53)    NULL,
    [JamkningSidoInk]          FLOAT (53)    NULL,
    [AMFej]                    BIT           NULL,
    [AMFarb]                   BIT           NULL,
    [AMFtjm]                   BIT           NULL,
    [ArbGivAvg1000]            BIT           NULL,
    [ArbGivAvgHalvtBasB]       BIT           NULL,
    [ArbGivAvgNedSattn]        FLOAT (53)    NULL,
    [ManadsLoneArt]            VARCHAR (3)   NULL,
    [TimLoneArt]               VARCHAR (3)   NULL,
    [BilFormanLoneArt]         VARCHAR (3)   NULL,
    [AckLon]                   MONEY         NULL,
    [AckSkatt]                 MONEY         NULL,
    [Active]                   BIT           NULL,
    [KeepTrans]                BIT           NULL,
    [Forskott]                 MONEY         NULL,
    [KodFormBil]               VARCHAR (8)   NULL,
    [SCBArbStNr]               VARCHAR (6)   NULL,
    [CompanyOwner]             BIT           NULL,
    [BilFromDatum]             VARCHAR (10)  NULL,
    [BilTomDatum]              VARCHAR (10)  NULL,
    [ArbGivAvgNedReg]          BIT           NULL,
    [AckForman]                MONEY         NULL,
    [CountedYearIncome]        MONEY         NULL,
    [Bearbetas]                BIT           NULL,
    [JournalFlagga]            BIT           NULL,
    [TidTrId]                  INT           NULL,
    [DebPris]                  MONEY         NULL,
    [Skattereduktion]          BIT           NULL,
    [Ack1]                     VARCHAR (3)   NULL,
    [Ack1_Antal]               FLOAT (53)    NULL,
    [Ack1_Belopp]              MONEY         NULL,
    [Ack2]                     VARCHAR (3)   NULL,
    [Ack2_Antal]               FLOAT (53)    NULL,
    [Ack2_Belopp]              MONEY         NULL,
    [Ack3]                     VARCHAR (3)   NULL,
    [Ack3_Antal]               FLOAT (53)    NULL,
    [Ack3_Belopp]              MONEY         NULL,
    [Ack4]                     VARCHAR (3)   NULL,
    [Ack4_Antal]               FLOAT (53)    NULL,
    [Ack4_Belopp]              MONEY         NULL,
    [Ack5]                     VARCHAR (3)   NULL,
    [Ack5_Antal]               FLOAT (53)    NULL,
    [Ack5_Belopp]              MONEY         NULL,
    [C1]                       FLOAT (53)    NULL,
    [C2]                       FLOAT (53)    NULL,
    [KontoManadsLoneArt]       VARCHAR (6)   NULL,
    [KontoTimLoneArt]          VARCHAR (6)   NULL,
    [bFackavgift]              BIT           NULL,
    [bSemesterErs]             BIT           NULL,
    [bSemesterOren]            BIT           NULL,
    [Fackavgift]               FLOAT (53)    NULL,
    [SemesterErs]              FLOAT (53)    NULL,
    [SemesterOren]             MONEY         NULL,
    [PrintToEmail]             BIT           NULL,
    [Email]                    VARCHAR (60)  NULL,
    [Email2]                   VARCHAR (60)  NULL,
    [ArbetsTidYear]            FLOAT (53)    NULL,
    [CSR]                      BIT           NULL,
    [Password]                 VARCHAR (20)  NULL,
    [ArbTidPerDag]             FLOAT (53)    NULL,
    [WebTidUser]               VARCHAR (20)  NULL,
    [WebTidAdmin]              BIT           NULL,
    [TidloggUser]              BIT           NULL,
    [ReducedAGA]               BIT           NULL,
    [TjansteSektor]            BIT           NULL,
    [TjansteSektorLow]         FLOAT (53)    NULL,
    [Born_2000]                BIT           NULL,
    [Fora_Undantag]            BIT           NULL,
    [Foretagsstod_Undantag]    BIT           NULL,
    [Bl_Yrkeskod]              VARCHAR (6)   NULL,
    [Bl_Yrkeskategori]         VARCHAR (4)   NULL,
    [Bl_Avtalsenlig_manadslon] MONEY         NULL,
    [Bl_Fordelningstal]        INT           NULL,
    [Konto]                    VARCHAR (6)   NULL,
    [ITP_Kst]                  VARCHAR (3)   NULL,
    [ITP_AvtalsplanId]         VARCHAR (3)   NULL,
    [ITP_Undantag]             BIT           NULL,
    [ITP_Status]               INT           NULL,
    [SSG_Active]               BIT           NULL,
    [SSG]                      MONEY         NULL,
    [SemesterAvtalId]          INT           NULL,
    [LoneAvtalId]              INT           NULL,
    [Fora_Uppm_Kod]            VARCHAR (1)   NULL,
    [MainUser]                 VARCHAR (4)   NULL,
    [Ensamstaende]             BIT           NULL,
    [FastaTillägg]             MONEY         NULL,
    [HeltidsLön]               MONEY         NULL,
    [AverageLön]               MONEY         NULL,
    [SemesterFaktor]           MONEY         NULL,
    [Stat_Arbetsplatsnummer]   INT           NULL,
    [Stat_Förbundsnummer]      INT           NULL,
    [Stat_Avtalskod]           INT           NULL,
    [Stat_Arbetstidart]        INT           NULL,
    [Stat_Yrkeskod]            INT           NULL,
    [Stat_Löneform]            INT           NULL,
    [Stat_FastLön]             MONEY         NULL,
    [Stat_CFAR]                INT           NULL,
    [Stat_Jobbstatus]          INT           NULL,
    [Stat_LänKommun]           VARCHAR (7)   NULL,
    [Stat_Undantag]            BIT           NULL,
    [VäxaStöd]                 BIT           NULL,
    [Jämkning]                 INT           NULL,
    [JämkningVärde]            MONEY         NULL,
    [Helglön]                  MONEY         NULL,
    [Sjuklön]                  MONEY         NULL,
    [KontoLon]                 VARCHAR (6)   NULL,
    [TimmarFrånSchema]         BIT           NULL,
    [fpe]                      MONEY         NULL,
    [pap]                      MONEY         NULL,
    [LandskodTIN]              VARCHAR (2)   NULL,
    [TIN]                      VARCHAR (20)  NULL,
    [ssg_karens]               MONEY         NULL,
    [SINK]                     BIT           NULL,
    [ASINK]                    BIT           NULL,
    [VerksamhetensArt]         VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

