CREATE TABLE [dbo].[Ftguppg] (
    [id]                VARCHAR (13)  NOT NULL,
    [name]              VARCHAR (40)  NULL,
    [master]            BIT           NULL,
    [Street]            VARCHAR (40)  NULL,
    [Box]               VARCHAR (40)  NULL,
    [Zip]               VARCHAR (6)   NULL,
    [City]              VARCHAR (40)  NULL,
    [Telephone]         VARCHAR (20)  NULL,
    [Telefax]           VARCHAR (20)  NULL,
    [Orgnr]             VARCHAR (20)  NULL,
    [Sortname]          VARCHAR (8)   NULL,
    [SNI]               VARCHAR (20)  NULL,
    [Pg]                VARCHAR (20)  NULL,
    [PgOCR]             VARCHAR (20)  NULL,
    [Bg]                VARCHAR (20)  NULL,
    [BgOCR]             VARCHAR (20)  NULL,
    [Password]          VARCHAR (24)  NULL,
    [Note]              VARCHAR (40)  NULL,
    [Email]             VARCHAR (60)  NULL,
    [Website]           VARCHAR (60)  NULL,
    [Country]           VARCHAR (20)  NULL,
    [EUid]              VARCHAR (20)  NULL,
    [ShowNamnFaktHead]  VARCHAR (40)  NULL,
    [FSkattText]        VARCHAR (40)  NULL,
    [Bankkonto]         VARCHAR (30)  NULL,
    [BankNamn]          VARCHAR (30)  NULL,
    [BankAdress]        VARCHAR (30)  NULL,
    [BankPostAdress]    VARCHAR (40)  NULL,
    [BokslutStatus]     INT           NULL,
    [Kategori]          VARCHAR (20)  NULL,
    [Ansvarig]          VARCHAR (20)  NULL,
    [Revisor]           VARCHAR (20)  NULL,
    [FakturaNote]       VARCHAR (MAX) NULL,
    [LoneNote]          VARCHAR (MAX) NULL,
    [Saete]             VARCHAR (40)  NULL,
    [RtaText]           VARCHAR (60)  NULL,
    [Remind1]           VARCHAR (MAX) NULL,
    [Remind2]           VARCHAR (MAX) NULL,
    [Remind3]           VARCHAR (MAX) NULL,
    [RemindTextToPrint] VARCHAR (MAX) NULL,
    [ReminderCost]      MONEY         NULL,
    [PgOCROnlyDigit]    VARCHAR (20)  NULL,
    [BgOCROnlyDigit]    VARCHAR (20)  NULL,
    [BankAnsvarig]      VARCHAR (30)  NULL,
    [IBAN]              VARCHAR (40)  NULL,
    [BIC]               VARCHAR (12)  NULL,
    [Mobil]             VARCHAR (20)  NULL,
    [ApiKey]            VARCHAR (60)  NULL,
    [Swish]             VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO

