CREATE TABLE [dbo].[KU10] (
    [AutoId]     INT          IDENTITY (1, 1) NOT NULL,
    [Ar]         VARCHAR (4)  NULL,
    [AnstId]     VARCHAR (8)  NULL,
    [PersonNr]   VARCHAR (20) NULL,
    [Name]       VARCHAR (50) NULL,
    [Box]        VARCHAR (50) NULL,
    [Zip]        VARCHAR (9)  NULL,
    [City]       VARCHAR (50) NULL,
    [08]         VARCHAR (2)  NULL,
    [09]         VARCHAR (2)  NULL,
    [40]         DATETIME     NULL,
    [61]         VARCHAR (1)  NULL,
    [60]         VARCHAR (6)  NULL,
    [01]         MONEY        NULL,
    [10]         MONEY        NULL,
    [11]         MONEY        NULL,
    [12]         MONEY        NULL,
    [13]         MONEY        NULL,
    [18]         MONEY        NULL,
    [20]         MONEY        NULL,
    [21]         MONEY        NULL,
    [22]         MONEY        NULL,
    [30]         MONEY        NULL,
    [31]         MONEY        NULL,
    [32]         MONEY        NULL,
    [25]         MONEY        NULL,
    [37]         MONEY        NULL,
    [35]         MONEY        NULL,
    [38]         MONEY        NULL,
    [39]         MONEY        NULL,
    [41]         VARCHAR (1)  NULL,
    [42]         VARCHAR (1)  NULL,
    [43]         VARCHAR (1)  NULL,
    [44]         VARCHAR (1)  NULL,
    [47]         VARCHAR (1)  NULL,
    [48]         VARCHAR (1)  NULL,
    [49]         VARCHAR (1)  NULL,
    [14]         VARCHAR (7)  NULL,
    [15]         VARCHAR (2)  NULL,
    [16]         MONEY        NULL,
    [17]         MONEY        NULL,
    [50]         VARCHAR (1)  NULL,
    [51]         VARCHAR (1)  NULL,
    [52]         VARCHAR (1)  NULL,
    [55]         VARCHAR (1)  NULL,
    [56]         VARCHAR (1)  NULL,
    [57]         VARCHAR (1)  NULL,
    [53]         VARCHAR (1)  NULL,
    [54]         VARCHAR (1)  NULL,
    [65]         VARCHAR (40) NULL,
    [66]         VARCHAR (36) NULL,
    [67]         VARCHAR (36) NULL,
    [68]         VARCHAR (36) NULL,
    [69]         VARCHAR (36) NULL,
    [70]         VARCHAR (40) NULL,
    [Street]     VARCHAR (40) NULL,
    [UP570]      VARCHAR (10) NULL,
    [UP40]       VARCHAR (10) NULL,
    [45]         VARCHAR (1)  NULL,
    [93]         VARCHAR (1)  NULL,
    [IB]         BIT          NULL,
    [UP205]      VARCHAR (1)  NULL,
    [SkattRegNr] VARCHAR (20) NULL,
    [76]         VARCHAR (5)  NULL,
    [59]         VARCHAR (1)  NULL
);


GO

