CREATE TABLE [dbo].[Kund] (
    [Id]                  VARCHAR (8)   NOT NULL,
    [Name]                VARCHAR (40)  NULL,
    [Street]              VARCHAR (40)  NULL,
    [Box]                 VARCHAR (40)  NULL,
    [Zip]                 VARCHAR (10)  NULL,
    [City]                VARCHAR (40)  NULL,
    [Telephone]           VARCHAR (20)  NULL,
    [Telefax]             VARCHAR (20)  NULL,
    [Email]               VARCHAR (80)  NULL,
    [Website]             VARCHAR (80)  NULL,
    [EUid]                VARCHAR (20)  NULL,
    [Pg]                  VARCHAR (20)  NULL,
    [Bg]                  VARCHAR (20)  NULL,
    [YourRef]             VARCHAR (40)  NULL,
    [BetVillkor]          VARCHAR (3)   NULL,
    [LevVillkor]          VARCHAR (6)   NULL,
    [LevSatt]             VARCHAR (6)   NULL,
    [Category]            VARCHAR (4)   NULL,
    [Currency]            VARCHAR (3)   NULL,
    [Kst]                 VARCHAR (6)   NULL,
    [Kb]                  VARCHAR (6)   NULL,
    [Pt]                  VARCHAR (16)  NULL,
    [SortName]            VARCHAR (8)   NULL,
    [YearTotal]           MONEY         NULL,
    [LastYearTotal]       MONEY         NULL,
    [Country]             VARCHAR (20)  NULL,
    [Momskod]             INT           NULL,
    [ReskontraKonto]      VARCHAR (6)   NULL,
    [KostKonto]           VARCHAR (6)   NULL,
    [Remarks]             VARCHAR (MAX) NULL,
    [Remind]              BIT           NULL,
    [RtaFakt]             BIT           NULL,
    [Faktura]             VARCHAR (40)  NULL,
    [Language]            SMALLINT      NULL,
    [Prislista]           SMALLINT      NULL,
    [Limit]               MONEY         NULL,
    [TidDebWait]          BIT           NULL,
    [Egen1]               VARCHAR (30)  NULL,
    [Egen2]               VARCHAR (30)  NULL,
    [Egen3]               VARCHAR (10)  NULL,
    [Egen4]               VARCHAR (10)  NULL,
    [Egen5]               VARCHAR (5)   NULL,
    [Egen6]               VARCHAR (5)   NULL,
    [Egen7]               VARCHAR (5)   NULL,
    [Egen8]               VARCHAR (5)   NULL,
    [Egen9]               VARCHAR (5)   NULL,
    [Egen10]              VARCHAR (5)   NULL,
    [Kndkat2]             VARCHAR (8)   NULL,
    [Kndkat3]             VARCHAR (8)   NULL,
    [Kndkat4]             VARCHAR (8)   NULL,
    [Kndkat5]             VARCHAR (8)   NULL,
    [Foreign]             BIT           NULL,
    [Ansvarig]            VARCHAR (40)  NULL,
    [Samfaktureras]       BIT           NULL,
    [Momsfri]             BIT           NULL,
    [EjFrakt]             BIT           NULL,
    [EjExpAvg]            BIT           NULL,
    [Autogiro_AF]         BIT           NULL,
    [Clearing]            VARCHAR (4)   NULL,
    [Bankkonto]           VARCHAR (12)  NULL,
    [FtgForm]             VARCHAR (5)   NULL,
    [FtgBransch]          VARCHAR (4)   NULL,
    [FtgAntAnst]          VARCHAR (4)   NULL,
    [RevisorKrav]         BIT           NULL,
    [TidPrisTyp]          SMALLINT      NULL,
    [TidPris]             MONEY         NULL,
    [TidMultiplikator]    FLOAT (53)    NULL,
    [AvtalsFaktura]       VARCHAR (40)  NULL,
    [Mobil]               VARCHAR (20)  NULL,
    [GrpStaffling]        VARCHAR (2)   NULL,
    [Password]            VARCHAR (255) NULL,
    [Intrastatland]       VARCHAR (2)   NULL,
    [Orgnr]               VARCHAR (15)  NULL,
    [Offert]              VARCHAR (40)  NULL,
    [Orderbek]            VARCHAR (40)  NULL,
    [Foljesedel]          VARCHAR (40)  NULL,
    [Paminnelse]          VARCHAR (40)  NULL,
    [RteFaktura]          VARCHAR (40)  NULL,
    [Created]             DATETIME      NULL,
    [CreatedBy]           VARCHAR (10)  NULL,
    [Updated]             DATETIME      NULL,
    [UpdatedBy]           VARCHAR (10)  NULL,
    [Avdelning]           VARCHAR (40)  NULL,
    [BetNrAg]             VARCHAR (16)  NULL,
    [OrgNrAg]             VARCHAR (16)  NULL,
    [Passiv]              BIT           NULL,
    [OffertToEmail]       BIT           NULL,
    [ObToEmail]           BIT           NULL,
    [FsToEmail]           BIT           NULL,
    [FaktToEmail]         BIT           NULL,
    [AoToEmail]           BIT           NULL,
    [KfToEmail]           BIT           NULL,
    [PaToEmail]           BIT           NULL,
    [RtToEmail]           BIT           NULL,
    [Filtyp]              SMALLINT      NULL,
    [Roundoff]            BIT           NULL,
    [Email_Of]            INT           NULL,
    [Email_Ob]            INT           NULL,
    [Email_Fs]            INT           NULL,
    [Email_Fa]            INT           NULL,
    [Email_Ao]            INT           NULL,
    [Email_Kf]            INT           NULL,
    [Email_Pa]            INT           NULL,
    [Email_Rt]            INT           NULL,
    [DelayFee]            BIT           NULL,
    [ConnectedCustomerId] VARCHAR (8)   NULL,
    [CompanyId]           VARCHAR (8)   NULL,
    [GLN]                 VARCHAR (40)  NULL,
    [PartyId]             VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

