CREATE TABLE [dbo].[Lev] (
    [Id]                        VARCHAR (8)   NOT NULL,
    [Name]                      VARCHAR (40)  NULL,
    [Street]                    VARCHAR (40)  NULL,
    [Box]                       VARCHAR (40)  NULL,
    [Zip]                       VARCHAR (10)  NULL,
    [City]                      VARCHAR (40)  NULL,
    [Telephone]                 VARCHAR (20)  NULL,
    [Telefax]                   VARCHAR (20)  NULL,
    [Email]                     VARCHAR (60)  NULL,
    [EUid]                      VARCHAR (20)  NULL,
    [Pg]                        VARCHAR (20)  NULL,
    [Bg]                        VARCHAR (20)  NULL,
    [YourRef]                   VARCHAR (40)  NULL,
    [BetVillkor]                VARCHAR (3)   NULL,
    [Category]                  VARCHAR (4)   NULL,
    [Currency]                  VARCHAR (3)   NULL,
    [CustIdAtLev]               VARCHAR (20)  NULL,
    [ReskontraKonto]            VARCHAR (6)   NULL,
    [KostKonto]                 VARCHAR (6)   NULL,
    [SenasteKostKonto]          VARCHAR (6)   NULL,
    [Kst]                       VARCHAR (6)   NULL,
    [Kb]                        VARCHAR (6)   NULL,
    [Pt]                        VARCHAR (16)  NULL,
    [SortName]                  VARCHAR (8)   NULL,
    [YearTotal]                 MONEY         NULL,
    [LastYearTotal]             MONEY         NULL,
    [Remarks]                   VARCHAR (MAX) NULL,
    [Country]                   VARCHAR (40)  NULL,
    [Momskod]                   INT           NULL,
    [Website]                   VARCHAR (60)  NULL,
    [EjAutoBg]                  BIT           NULL,
    [EjAutoPg]                  BIT           NULL,
    [Autogiro]                  BIT           NULL,
    [DefaultOCR]                VARCHAR (30)  NULL,
    [Attestansvarig]            VARCHAR (3)   NULL,
    [Passiv]                    BIT           NULL,
    [Utland_Kostnadsdebitering] VARCHAR (1)   NULL,
    [Utland_Betalmetod]         VARCHAR (1)   NULL,
    [Utland_Landkod]            VARCHAR (2)   NULL,
    [Utland_BIC]                VARCHAR (14)  NULL,
    [Utland_Kontonr]            VARCHAR (34)  NULL,
    [Utland_Bank]               VARCHAR (30)  NULL,
    [Utland_Riksbankskod]       VARCHAR (3)   NULL,
    [Utland_Belastningskonto]   VARCHAR (1)   NULL,
    [Utland_Valutakonto]        VARCHAR (35)  NULL,
    [Utland_Valutaficka]        VARCHAR (3)   NULL,
    [Kontonummer]               VARCHAR (20)  NULL,
    [PartyId]                   VARCHAR (20)  NULL,
    [Orgnr]                     VARCHAR (15)  NULL,
    [GLN]                       VARCHAR (40)  NULL,
    [autoregfakt]               BIT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

