CREATE TABLE [dbo].[LevBet] (
    [Id]                        INT          NOT NULL,
    [LopNr]                     INT          NULL,
    [FaktId]                    INT          NULL,
    [LevId]                     VARCHAR (8)  NULL,
    [FaktNr]                    VARCHAR (30) NULL,
    [OCRnr]                     VARCHAR (30) NULL,
    [Datum]                     DATETIME     NULL,
    [BeloppVal]                 MONEY        NULL,
    [BeloppSek]                 MONEY        NULL,
    [Valuta]                    VARCHAR (3)  NULL,
    [Konto]                     VARCHAR (6)  NULL,
    [BortKontering]             BIT          NULL,
    [Uppdaterad]                BIT          NULL,
    [User]                      VARCHAR (8)  NULL,
    [LevBetMetod]               VARCHAR (16) NULL,
    [ExternBevakning]           BIT          NULL,
    [UtlandBevakning]           BIT          NULL,
    [InLastModemFile]           BIT          NULL,
    [BuntId]                    INT          NULL,
    [Bgbevakning]               BIT          NULL,
    [Pgbevakning]               BIT          NULL,
    [VerSerie]                  VARCHAR (1)  NULL,
    [VerNo]                     INT          NULL,
    [VerDatum]                  DATETIME     NULL,
    [BetalMetod]                SMALLINT     NULL,
    [Mottagarkonto]             VARCHAR (40) NULL,
    [Uppdragsdatum]             DATETIME     NULL,
    [Uppdragslopnr]             INT          NULL,
    [JournalNo]                 INT          NULL,
    [BevakningsJournalDatum]    DATETIME     NULL,
    [BevakningsJournalNo]       INT          NULL,
    [Utland_Kostnadsdebitering] VARCHAR (1)  NULL,
    [Utland_Betalmetod]         VARCHAR (1)  NULL,
    [Utland_Riksbankskod]       VARCHAR (3)  NULL,
    [Utland_Belastningskonto]   VARCHAR (1)  NULL,
    [Utland_Valutakonto]        VARCHAR (35) NULL,
    [Utland_Valutaficka]        VARCHAR (3)  NULL,
    [Utland_Extra]              VARCHAR (1)  NULL,
    [Utland_Extra2]             VARCHAR (1)  NULL,
    [Utland_Omrakning]          BIT          NULL,
    [VerTrId]                   INT          NULL,
    [Pain001Id]                 VARCHAR (16) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

