CREATE TABLE [dbo].[Levfakt] (
    [AutoId]               INT           IDENTITY (1, 1) NOT NULL,
    [Id]                   INT           NOT NULL,
    [LevId]                VARCHAR (8)   NULL,
    [FaktNr]               VARCHAR (30)  NULL,
    [OCRnr]                VARCHAR (30)  NULL,
    [FaktDatum]            DATETIME      NULL,
    [FfDatum]              DATETIME      NULL,
    [BeloppVal]            MONEY         NULL,
    [BeloppSek]            MONEY         NULL,
    [BetaltVal]            MONEY         NULL,
    [BetaltSek]            MONEY         NULL,
    [LastBetDatum]         DATETIME      NULL,
    [Valuta]               VARCHAR (3)   NULL,
    [AttestKod]            VARCHAR (3)   NULL,
    [BetSparr]             BIT           NULL,
    [User]                 VARCHAR (8)   NULL,
    [Attesterad]           BIT           NULL,
    [Betald]               BIT           NULL,
    [Uppdaterad]           BIT           NULL,
    [ExternBevakning]      BIT           NULL,
    [PausaUppdatering]     BIT           NULL,
    [LopNr]                INT           NULL,
    [Kst]                  VARCHAR (6)   NULL,
    [Kb]                   VARCHAR (6)   NULL,
    [Pt]                   VARCHAR (16)  NULL,
    [VerSerie]             VARCHAR (1)   NULL,
    [VerNo]                INT           NULL,
    [VerDatum]             DATETIME      NULL,
    [JournalNo]            INT           NULL,
    [AttestkonteringGjord] BIT           NULL,
    [AttestVerSerie]       VARCHAR (1)   NULL,
    [AttestVerNo]          INT           NULL,
    [AttestVerDatum]       DATETIME      NULL,
    [AttestJournalNo]      INT           NULL,
    [BetalTyp]             SMALLINT      NULL,
    [VerTrId]              INT           NULL,
    [Kommentar]            VARCHAR (255) NULL,
    [ExtInvoiceId]         BIGINT        NULL,
    [AutoReg]              BIT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

