CREATE TABLE [dbo].[Lon] (
    [Id]                     INT          NOT NULL,
    [AnstId]                 VARCHAR (8)  NULL,
    [UtbetDatum]             DATETIME     NULL,
    [Skattetabell]           FLOAT (53)   NULL,
    [SkattegrundandeBelopp]  MONEY        NULL,
    [Formaner]               MONEY        NULL,
    [Ersattning]             MONEY        NULL,
    [Avdrag]                 MONEY        NULL,
    [ErsattningTotalt]       MONEY        NULL,
    [PreliminarSkatt]        MONEY        NULL,
    [Forskott]               MONEY        NULL,
    [Kvarskatt]              MONEY        NULL,
    [Avrundat]               MONEY        NULL,
    [UtbetaltBelopp]         MONEY        NULL,
    [SemesterDagar_Betalda]  FLOAT (53)   NULL,
    [SemesterDagar_Obetalda] FLOAT (53)   NULL,
    [SemesterDagar_Sparade]  FLOAT (53)   NULL,
    [SemesterDagar_Forskott] FLOAT (53)   NULL,
    [SemesterErsattning]     MONEY        NULL,
    [SemesterErsattningOren] MONEY        NULL,
    [Fackavgifter]           MONEY        NULL,
    [Arbetsgivaravgifter]    MONEY        NULL,
    [Sarskildloneskatter]    MONEY        NULL,
    [RegionalNedsattning]    MONEY        NULL,
    [NedsTjSektor]           FLOAT (53)   NULL,
    [Amf_Antal]              FLOAT (53)   NULL,
    [Amf_Belopp]             MONEY        NULL,
    [TjansteSektor_Andel]    FLOAT (53)   NULL,
    [TjansteSektor_Procent]  FLOAT (53)   NULL,
    [TjansteSektor_Underlag] MONEY        NULL,
    [TjansteSektor_Belopp]   MONEY        NULL,
    [User]                   VARCHAR (10) NULL,
    [Uppdaterad]             BIT          NULL,
    [Utskriven]              BIT          NULL,
    [KlarForUtskrift]        BIT          NULL,
    [JournalNo]              INT          NULL,
    [ByEmail]                BIT          NULL,
    [Exporterad]             BIT          NULL,
    [Updated]                DATETIME     NULL,
    [UpdatedBy]              VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

