CREATE TABLE [dbo].[LoneArt] (
    [Id]                    VARCHAR (5)  NOT NULL,
    [Text]                  VARCHAR (60) NULL,
    [Konto]                 VARCHAR (6)  NULL,
    [KoppladLoneArt]        VARCHAR (5)  NULL,
    [Typ]                   SMALLINT     NULL,
    [ArbGivAvg]             SMALLINT     NULL,
    [UseDate]               BIT          NULL,
    [UseAntal]              BIT          NULL,
    [UseBelopp]             BIT          NULL,
    [UseKst]                BIT          NULL,
    [UseKb]                 BIT          NULL,
    [UsePt]                 BIT          NULL,
    [UseAnm]                BIT          NULL,
    [AMFtimAntal]           BIT          NULL,
    [AMFlonBelopp]          BIT          NULL,
    [SEMcountBet]           BIT          NULL,
    [SEMcountObet]          BIT          NULL,
    [SEMcountSpar]          BIT          NULL,
    [SEMcountForskott]      BIT          NULL,
    [KontrollUppg]          SMALLINT     NULL,
    [KostnAvdrag]           FLOAT (53)   NULL,
    [AgainEveryPeriod]      BIT          NULL,
    [Konto2]                VARCHAR (6)  NULL,
    [Formel]                VARCHAR (60) NULL,
    [Belopp]                MONEY        NULL,
    [SemGr]                 BIT          NULL,
    [SemGrProc]             FLOAT (53)   NULL,
    [FackGr]                BIT          NULL,
    [FackGrProc]            FLOAT (53)   NULL,
    [SemOreGr]              BIT          NULL,
    [SemOreGrBelopp]        MONEY        NULL,
    [SemKonto]              VARCHAR (6)  NULL,
    [FackKonto]             VARCHAR (6)  NULL,
    [SemOreKonto]           VARCHAR (6)  NULL,
    [Ack1]                  VARCHAR (3)  NULL,
    [Ack2]                  VARCHAR (3)  NULL,
    [Ack3]                  VARCHAR (3)  NULL,
    [Ack4]                  VARCHAR (3)  NULL,
    [Ack5]                  VARCHAR (3)  NULL,
    [SemUtbet]              BIT          NULL,
    [Granskningslista]      BIT          NULL,
    [Granskningslista_Tim]  BIT          NULL,
    [Sjukfranvaro]          BIT          NULL,
    [Sjukfranvaro_Timmar]   FLOAT (53)   NULL,
    [Fora_Undantag]         BIT          NULL,
    [Timredovisning]        BIT          NULL,
    [Kst]                   VARCHAR (6)  NULL,
    [Kb]                    VARCHAR (6)  NULL,
    [Pt]                    VARCHAR (16) NULL,
    [Bl_Arbetade_Timmar]    BIT          NULL,
    [Bl_Lonesumma]          BIT          NULL,
    [Bl_OB_tillagg]         BIT          NULL,
    [Bl_Overtid_Timmar]     BIT          NULL,
    [Bl_Overtidstillagg]    BIT          NULL,
    [HideOnPrint]           BIT          NULL,
    [ITP_Undantag]          BIT          NULL,
    [Enhet]                 VARCHAR (10) NULL,
    [Sjuklonekostnad]       BIT          NULL,
    [RorligLon]             BIT          NULL,
    [UnderlagProcentRegeln] BIT          NULL,
    [Kod]                   VARCHAR (3)  NULL,
    [ArbetadTid]            BIT          NULL,
    [SemGrTid]              BIT          NULL,
    [SemGrErsKorttidsPerm]  BIT          NULL,
    [KontoArb]              VARCHAR (6)  NULL,
    [KontoTjm]              VARCHAR (6)  NULL,
    [PrioKontoFromAnst]     BIT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

