CREATE TABLE [dbo].[Ord] (
    [OrderNr]                 INT           NOT NULL,
    [Typ]                     SMALLINT      NOT NULL,
    [KundId]                  VARCHAR (8)   NULL,
    [Name]                    VARCHAR (40)  NULL,
    [Street]                  VARCHAR (40)  NULL,
    [Box]                     VARCHAR (40)  NULL,
    [Zip]                     VARCHAR (10)  NULL,
    [City]                    VARCHAR (40)  NULL,
    [CountryKod]              SMALLINT      NULL,
    [Language]                SMALLINT      NULL,
    [DelNr]                   VARCHAR (8)   NULL,
    [DelName]                 VARCHAR (40)  NULL,
    [DelStreet]               VARCHAR (40)  NULL,
    [DelBox]                  VARCHAR (40)  NULL,
    [DelZip]                  VARCHAR (10)  NULL,
    [DelCity]                 VARCHAR (40)  NULL,
    [OurRef]                  VARCHAR (40)  NULL,
    [YourRef]                 VARCHAR (40)  NULL,
    [Kst]                     VARCHAR (8)   NULL,
    [Kb]                      VARCHAR (8)   NULL,
    [Pt]                      VARCHAR (16)  NULL,
    [Remark]                  VARCHAR (40)  NULL,
    [TotRabProc]              FLOAT (53)    NULL,
    [TotRabBel]               MONEY         NULL,
    [BetVillkor]              VARCHAR (3)   NULL,
    [BetVillkorText]          VARCHAR (40)  NULL,
    [LevVillkor]              VARCHAR (6)   NULL,
    [LevVillkorText]          VARCHAR (40)  NULL,
    [LevSatt]                 VARCHAR (6)   NULL,
    [LevSattText]             VARCHAR (40)  NULL,
    [OrderSummaNetto]         MONEY         NULL,
    [OrderSummaBrutto]        MONEY         NULL,
    [OrderMomsSumma]          MONEY         NULL,
    [OrderTotal]              MONEY         NULL,
    [TBProc]                  FLOAT (53)    NULL,
    [LevDatum]                DATETIME      NULL,
    [FaktNr]                  INT           NULL,
    [FaktDatum]               DATETIME      NULL,
    [FaktFfDatum]             DATETIME      NULL,
    [FaktStop]                BIT           NULL,
    [Bearbetas]               BIT           NULL,
    [RekNr]                   VARCHAR (20)  NULL,
    [Currency]                VARCHAR (3)   NULL,
    [Notering]                VARCHAR (MAX) NULL,
    [DelCountry]              VARCHAR (20)  NULL,
    [Country]                 VARCHAR (20)  NULL,
    [NextLine]                SMALLINT      NULL,
    [MoneyPayed]              MONEY         NULL,
    [MoneyGot]                MONEY         NULL,
    [MoneyBack]               MONEY         NULL,
    [User]                    VARCHAR (10)  NULL,
    [YourOrderNr]             VARCHAR (20)  NULL,
    [OrderDatum]              DATETIME      NULL,
    [OrderSummaInPris]        MONEY         NULL,
    [TBBelopp]                MONEY         NULL,
    [ExpAvgift]               MONEY         NULL,
    [Vikt]                    FLOAT (53)    NULL,
    [Volym]                   FLOAT (53)    NULL,
    [Frakt]                   MONEY         NULL,
    [OresUtj]                 MONEY         NULL,
    [OrderSummaRader]         MONEY         NULL,
    [Uppdaterad]              BIT           NULL,
    [FaUtskriven]             BIT           NULL,
    [FsUtskriven]             BIT           NULL,
    [ObUtskriven]             BIT           NULL,
    [OffertUtskriven]         BIT           NULL,
    [KlarAttFakturera]        BIT           NULL,
    [MomsFritt]               BIT           NULL,
    [OrderTyp]                VARCHAR (1)   NULL,
    [RestorderText]           VARCHAR (9)   NULL,
    [DelLevererad]            BIT           NULL,
    [KvittoNr]                INT           NULL,
    [DocumentRubrik]          VARCHAR (20)  NULL,
    [AvtalAntalFaktOmg]       SMALLINT      NULL,
    [AvtalNextFaktOmg]        SMALLINT      NULL,
    [AvtalMonthPerFaktOmg]    SMALLINT      NULL,
    [AvtalNextPeriod]         VARCHAR (6)   NULL,
    [AvtalFreeMonth]          VARCHAR (6)   NULL,
    [AvtalKvm]                FLOAT (53)    NULL,
    [PayKonto]                VARCHAR (6)   NULL,
    [OCR_Ref]                 VARCHAR (15)  NULL,
    [OCR_Kronor]              VARCHAR (10)  NULL,
    [OCR_Ore]                 VARCHAR (2)   NULL,
    [OCR_Check]               VARCHAR (1)   NULL,
    [Rta]                     FLOAT (53)    NULL,
    [MomsBelopp1]             MONEY         NULL,
    [MomsBelopp2]             MONEY         NULL,
    [MomsBelopp3]             MONEY         NULL,
    [MomsBelopp4]             MONEY         NULL,
    [MomsBelopp5]             MONEY         NULL,
    [MomsBelopp6]             MONEY         NULL,
    [MomsBelopp7]             MONEY         NULL,
    [BuMoms0]                 MONEY         NULL,
    [BuMoms1]                 MONEY         NULL,
    [BuMoms2]                 MONEY         NULL,
    [BuMoms3]                 MONEY         NULL,
    [BuMoms4]                 MONEY         NULL,
    [BuMoms5]                 MONEY         NULL,
    [BuMoms6]                 MONEY         NULL,
    [Moms1Sek]                MONEY         NULL,
    [Moms2Sek]                MONEY         NULL,
    [Moms3Sek]                MONEY         NULL,
    [Moms4Sek]                MONEY         NULL,
    [Moms5Sek]                MONEY         NULL,
    [Moms6Sek]                MONEY         NULL,
    [MomsTotSek]              MONEY         NULL,
    [Exchange]                FLOAT (53)    NULL,
    [AvtalPeriod]             VARCHAR (13)  NULL,
    [AvtalPeriodT]            VARCHAR (35)  NULL,
    [AvtalNr]                 INT           NULL,
    [Kampanj]                 INT           NULL,
    [OrderSummaRaderInklMoms] MONEY         NULL,
    [DelRef]                  VARCHAR (40)  NULL,
    [MomsSatsFrakt]           FLOAT (53)    NULL,
    [Seller]                  VARCHAR (10)  NULL,
    [Updated]                 DATETIME      NULL,
    [UpdatedBy]               VARCHAR (10)  NULL,
    [KundId2]                 VARCHAR (8)   NULL,
    [JournalNo]               INT           NULL,
    [Selected_User]           VARCHAR (10)  NULL,
    [ByEmail]                 VARCHAR (1)   NULL,
    [Avdelning]               VARCHAR (40)  NULL,
    [FromOffertNr]            INT           NULL,
    [ExporteradFaktura]       VARCHAR (10)  NULL,
    [ExporteraFaktura]        BIT           NULL,
    [Cur_Value]               FLOAT (53)    NULL,
    [SentToMobile]            BIT           NULL,
    [Ursprung]                VARCHAR (1)   NULL,
    [Levtyp]                  SMALLINT      NULL,
    [Passed]                  BIT           NULL,
    [Frakttyp]                SMALLINT      NULL,
    [ProdGrSumma1]            MONEY         NULL,
    [ProdGrSumma2]            MONEY         NULL,
    [ProdGrSumma3]            MONEY         NULL,
    [KolliId]                 VARCHAR (13)  NULL,
    [autogiro_periodkod]      SMALLINT      NULL,
    [RotRutSumma]             MONEY         NULL,
    [MomsSatsExpAvgift]       FLOAT (53)    NULL,
    [Absolut_Netto]           MONEY         NULL,
    [Absolut_Moms]            MONEY         NULL,
    [Absolut_Total]           MONEY         NULL,
    [Prisavtal]               VARCHAR (1)   NULL,
    [Email]                   VARCHAR (255) NULL,
    [EmailNotify]             VARCHAR (60)  NULL,
    [Telephone]               VARCHAR (40)  NULL,
    [Blankett]                VARCHAR (40)  NULL,
    [FakturaNote]             VARCHAR (MAX) NULL,
    [ExpAvgiftInkMoms]        MONEY         NULL,
    [FraktInkMoms]            MONEY         NULL,
    [OfferId]                 VARCHAR (10)  NULL,
    [CreatedBy]               VARCHAR (10)  NULL,
    [IncludeAttachments]      BIT           NULL,
    [eFakturaId]              INT           NULL,
    [MassfaktNr]              INT           NULL,
    [AutoId]                  INT           IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([OrderNr] ASC, [Typ] ASC)
);


GO

CREATE NONCLUSTERED INDEX [KundIdKey]
    ON [dbo].[Ord]([KundId] ASC);


GO

