CREATE TABLE [dbo].[OrderLn] (
    [OrderNr]                   INT          NOT NULL,
    [RadNr]                     SMALLINT     NOT NULL,
    [ProdNr]                    VARCHAR (18) NULL,
    [Beskr]                     VARCHAR (80) NULL,
    [MomsKod]                   VARCHAR (8)  NULL,
    [Kb]                        VARCHAR (6)  NULL,
    [Kst]                       VARCHAR (6)  NULL,
    [Pt]                        VARCHAR (16) NULL,
    [UtskOe]                    BIT          NULL,
    [UtskFs]                    BIT          NULL,
    [BestAntal]                 FLOAT (53)   NULL,
    [LevAntal]                  FLOAT (53)   NULL,
    [LevAntalTot]               FLOAT (53)   NULL,
    [RestAntal]                 FLOAT (53)   NULL,
    [PrisTotalInklMoms]         MONEY        NULL,
    [RabattProc]                FLOAT (53)   NULL,
    [RabattBelopp]              MONEY        NULL,
    [RegDatum]                  DATETIME     NULL,
    [Enhet]                     VARCHAR (10) NULL,
    [Vikt]                      FLOAT (53)   NULL,
    [Volym]                     FLOAT (53)   NULL,
    [Currency]                  VARCHAR (3)  NULL,
    [aPris]                     MONEY        NULL,
    [Typ]                       SMALLINT     NOT NULL,
    [PrisNetto]                 MONEY        NULL,
    [PrisBrutto]                MONEY        NULL,
    [PrisMoms]                  MONEY        NULL,
    [TBBelopp]                  MONEY        NULL,
    [PrisIn]                    MONEY        NULL,
    [TBProc]                    FLOAT (53)   NULL,
    [aPrisInklMoms]             MONEY        NULL,
    [AnstId]                    VARCHAR (8)  NULL,
    [Konto]                     VARCHAR (6)  NULL,
    [Remark]                    VARCHAR (80) NULL,
    [LineType]                  VARCHAR (10) NULL,
    [LeveransDatum]             VARCHAR (20) NULL,
    [Updated]                   DATETIME     NULL,
    [UpdatedBy]                 VARCHAR (10) NULL,
    [Lagerplats]                VARCHAR (10) NULL,
    [SupressOnInvoice]          BIT          NULL,
    [DatumFrom]                 DATETIME     NULL,
    [DatumTom]                  DATETIME     NULL,
    [Absolut_Radtotal]          MONEY        NULL,
    [RabattTyp]                 SMALLINT     NULL,
    [AntalManaderPeriodisering] SMALLINT     NULL,
    [RowProperty]               SMALLINT     NULL,
    [AutoId]                    INT          IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([OrderNr] ASC, [Typ] ASC, [RadNr] ASC)
);


GO

