CREATE TABLE [dbo].[RotRutPrint] (
    [AutoId]                        INT          IDENTITY (1, 1) NOT NULL,
    [YYYY]                          INT          NULL,
    [Nr]                            INT          NULL,
    [Typ]                           INT          NULL,
    [Datum]                         DATETIME     NULL,
    [RadNr]                         INT          NULL,
    [PersonNr]                      VARCHAR (12) NULL,
    [OrgNr]                         VARCHAR (12) NULL,
    [BetalDatum]                    DATETIME     NULL,
    [PrisArbete]                    MONEY        NULL,
    [BetaltBelopp]                  MONEY        NULL,
    [Belopp]                        MONEY        NULL,
    [Fastighet]                     VARCHAR (40) NULL,
    [FaktNr]                        INT          NULL,
    [FaktNrSKV]                     INT          NULL,
    [FileCreated]                   BIT          NULL,
    [Summa]                         MONEY        NULL,
    [LghBet]                        VARCHAR (40) NULL,
    [OvrigaKostnader]               INT          NULL,
    [Bygg_Timmar]                   INT          NULL,
    [Bygg_Material]                 INT          NULL,
    [El_Timmar]                     INT          NULL,
    [El_Material]                   INT          NULL,
    [Glasarbete_Timmar]             INT          NULL,
    [Glasarbete_Material]           INT          NULL,
    [Markarbete_Timmar]             INT          NULL,
    [Markarbete_Material]           INT          NULL,
    [Murning_Timmar]                INT          NULL,
    [Murning_Material]              INT          NULL,
    [MalningTapetsering_Timmar]     INT          NULL,
    [MalningTapetsering_Material]   INT          NULL,
    [Vvs_Timmar]                    INT          NULL,
    [Vvs_Material]                  INT          NULL,
    [Stadning_Timmar]               INT          NULL,
    [Stadning_Material]             INT          NULL,
    [HemtextilOchKladvard_Timmar]   INT          NULL,
    [HemtextilOchKladvard_Material] INT          NULL,
    [ItTjanster_Timmar]             INT          NULL,
    [ItTjanster_Material]           INT          NULL,
    [Snoskottning_Timmar]           INT          NULL,
    [Snoskottning_Material]         INT          NULL,
    [Tradgardsarbete_Timmar]        INT          NULL,
    [Tradgardsarbete_Material]      INT          NULL,
    [Barnpassning_Timmar]           INT          NULL,
    [Barnpassning_Material]         INT          NULL,
    [Annanomsorg_Timmar]            INT          NULL,
    [Annanomsorg_Material]          INT          NULL,
    [FlyttTjanster_Timmar]          INT          NULL,
    [FlyttTjanster_Material]        INT          NULL,
    [RepVitvaror_Timmar]            INT          NULL,
    [RepVitvaror_Material]          INT          NULL,
    [Tvätteritjänster_Timmar]       INT          NULL,
    [Möbleringstjänster_Timmar]     INT          NULL,
    [Möbleringstjänster_Material]   INT          NULL,
    [Transporttjänster_Timmar]      INT          NULL,
    [Tillsynstjänster_Timmar]       INT          NULL,
    [Tillsynstjänster_Material]     INT          NULL,
    [Solceller_Timmar]              INT          NULL,
    [Solceller_Material]            INT          NULL,
    [EgenprodEl_Timmar]             INT          NULL,
    [EgenprodEl_Material]           INT          NULL,
    [Laddningspunkt_Timmar]         INT          NULL,
    [Laddningspunkt_Material]       INT          NULL
);


GO

