CREATE TABLE [dbo].[RotRut] (
    [Id]                            INT          NOT NULL,
    [Typ]                           INT          NULL,
    [FaktNr]                        INT          NULL,
    [OrderNr]                       INT          NULL,
    [KundId]                        VARCHAR (8)  NULL,
    [PersonNr1]                     VARCHAR (12) NULL,
    [PersonNr2]                     VARCHAR (12) NULL,
    [PartOf1]                       FLOAT (53)   NULL,
    [PartOf2]                       FLOAT (53)   NULL,
    [Name]                          VARCHAR (40) NULL,
    [OrgNr]                         VARCHAR (12) NULL,
    [Fastighet]                     VARCHAR (40) NULL,
    [Adress]                        VARCHAR (40) NULL,
    [Zip]                           VARCHAR (10) NULL,
    [City]                          VARCHAR (40) NULL,
    [Forward]                       BIT          NULL,
    [Belopp]                        MONEY        NULL,
    [PrisArbete]                    MONEY        NULL,
    [Betaldatum]                    DATETIME     NULL,
    [Created]                       DATETIME     NULL,
    [ForwardDate]                   DATETIME     NULL,
    [FaktNrSKV]                     INT          NULL,
    [LghBet]                        VARCHAR (40) NULL,
    [OvrigaKostnader]               INT          NULL,
    [Bygg_Timmar]                   INT          NULL,
    [Bygg_Material]                 INT          NULL,
    [El_Timmar]                     INT          NULL,
    [El_Material]                   INT          NULL,
    [Glasarbete_Timmar]             INT          NULL,
    [Glasarbete_Material]           INT          NULL,
    [Markarbete_Timmar]             INT          NULL,
    [Markarbete_Material]           INT          NULL,
    [Murning_Timmar]                INT          NULL,
    [Murning_Material]              INT          NULL,
    [MalningTapetsering_Timmar]     INT          NULL,
    [MalningTapetsering_Material]   INT          NULL,
    [Vvs_Timmar]                    INT          NULL,
    [Vvs_Material]                  INT          NULL,
    [Stadning_Timmar]               INT          NULL,
    [Stadning_Material]             INT          NULL,
    [HemtextilOchKladvard_Timmar]   INT          NULL,
    [HemtextilOchKladvard_Material] INT          NULL,
    [ItTjanster_Timmar]             INT          NULL,
    [ItTjanster_Material]           INT          NULL,
    [Snoskottning_Timmar]           INT          NULL,
    [Snoskottning_Material]         INT          NULL,
    [Tradgardsarbete_Timmar]        INT          NULL,
    [Tradgardsarbete_Material]      INT          NULL,
    [Barnpassning_Timmar]           INT          NULL,
    [Barnpassning_Material]         INT          NULL,
    [Annanomsorg_Timmar]            INT          NULL,
    [Annanomsorg_Material]          INT          NULL,
    [FlyttTjanster_Timmar]          INT          NULL,
    [FlyttTjanster_Material]        INT          NULL,
    [RepVitvaror_Timmar]            INT          NULL,
    [RepVitvaror_Material]          INT          NULL,
    [TvatteriTjanster_Timmar]       INT          NULL,
    [MobleringsTjanster_Timmar]     INT          NULL,
    [TransportTjanster_Timmar]      INT          NULL,
    [TillsynsTjanster_Timmar]       INT          NULL,
    [MobleringsTjanster_Material]   INT          NULL,
    [TillsynsTjanster_Material]     INT          NULL,
    [Solceller_Timmar]              INT          NULL,
    [Solceller_Material]            INT          NULL,
    [EgenprodEl_Timmar]             INT          NULL,
    [EgenprodEl_Material]           INT          NULL,
    [Laddningspunkt_Timmar]         INT          NULL,
    [Laddningspunkt_Material]       INT          NULL,
    [Manuell_Count]                 BIT          NULL,
    [BeloppPersonNr1]               MONEY        NULL,
    [BeloppPersonNr2]               MONEY        NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

