CREATE TABLE [dbo].[Salary] (
    [Id]                              INT           NOT NULL,
    [AnstId]                          VARCHAR (8)   NULL,
    [Name]                            VARCHAR (40)  NULL,
    [Street]                          VARCHAR (40)  NULL,
    [Box]                             VARCHAR (40)  NULL,
    [Zip]                             VARCHAR (10)  NULL,
    [City]                            VARCHAR (40)  NULL,
    [UtbetDatum]                      DATETIME      NULL,
    [Skattetabell]                    FLOAT (53)    NULL,
    [SkattegrundandeBelopp]           MONEY         NULL,
    [Bruttolon]                       MONEY         NULL,
    [Formaner]                        MONEY         NULL,
    [Ersattning]                      MONEY         NULL,
    [Avdrag]                          MONEY         NULL,
    [PreliminarSkatt]                 MONEY         NULL,
    [Forskott]                        MONEY         NULL,
    [Kvarskatt]                       MONEY         NULL,
    [Avrundat]                        MONEY         NULL,
    [UtbetaltBelopp]                  MONEY         NULL,
    [SemesterDagar_Betalda]           FLOAT (53)    NULL,
    [SemesterDagar_Obetalda]          FLOAT (53)    NULL,
    [SemesterDagar_Sparade]           FLOAT (53)    NULL,
    [SemesterDagar_Forskott]          FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År1]       FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År2]       FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År3]       FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År4]       FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År5]       FLOAT (53)    NULL,
    [SemesterDagar_Sparade_År6]       FLOAT (53)    NULL,
    [SemesterDagar_Betalda_Saldo]     FLOAT (53)    NULL,
    [SemesterDagar_Obetalda_Saldo]    FLOAT (53)    NULL,
    [SemesterDagar_Sparade_Saldo]     FLOAT (53)    NULL,
    [SemesterDagar_Forskott_Saldo]    FLOAT (53)    NULL,
    [SemesterDagar_Preliminära_Saldo] FLOAT (53)    NULL,
    [SemesterDagar_Preliminära]       FLOAT (53)    NULL,
    [SemesterErsattning]              MONEY         NULL,
    [SemesterErsattningOren]          MONEY         NULL,
    [SemesterSociala]                 MONEY         NULL,
    [Fackavgifter]                    MONEY         NULL,
    [Arbetsgivaravgifter_Procent]     FLOAT (53)    NULL,
    [Arbetsgivaravgifter]             MONEY         NULL,
    [Sarskildloneskatter_Procent]     FLOAT (53)    NULL,
    [Sarskildloneskatter]             MONEY         NULL,
    [RegionalNedsattning]             MONEY         NULL,
    [Amf_Antal]                       FLOAT (53)    NULL,
    [Amf_Belopp]                      MONEY         NULL,
    [SemesterDagar_Uttag]             FLOAT (53)    NULL,
    [PeriodText]                      VARCHAR (40)  NULL,
    [AckLon]                          MONEY         NULL,
    [AckSkatt]                        MONEY         NULL,
    [AckForman]                       MONEY         NULL,
    [Ack1]                            VARCHAR (3)   NULL,
    [Ack1_Text]                       VARCHAR (30)  NULL,
    [Ack1_Antal]                      FLOAT (53)    NULL,
    [Ack1_Belopp]                     MONEY         NULL,
    [Ack2]                            VARCHAR (3)   NULL,
    [Ack2_Text]                       VARCHAR (30)  NULL,
    [Ack2_Antal]                      FLOAT (53)    NULL,
    [Ack2_Belopp]                     MONEY         NULL,
    [Ack3]                            VARCHAR (3)   NULL,
    [Ack3_Text]                       VARCHAR (30)  NULL,
    [Ack3_Antal]                      FLOAT (53)    NULL,
    [Ack3_Belopp]                     MONEY         NULL,
    [Ack4]                            VARCHAR (3)   NULL,
    [Ack4_Text]                       VARCHAR (30)  NULL,
    [Ack4_Antal]                      FLOAT (53)    NULL,
    [Ack4_Belopp]                     MONEY         NULL,
    [Ack5]                            VARCHAR (3)   NULL,
    [Ack5_Text]                       VARCHAR (30)  NULL,
    [Ack5_Antal]                      FLOAT (53)    NULL,
    [Ack5_Belopp]                     MONEY         NULL,
    [Ack1_Antal_Saldo]                FLOAT (53)    NULL,
    [Ack1_Belopp_Saldo]               MONEY         NULL,
    [Ack2_Antal_Saldo]                FLOAT (53)    NULL,
    [Ack2_Belopp_Saldo]               MONEY         NULL,
    [Ack3_Antal_Saldo]                FLOAT (53)    NULL,
    [Ack3_Belopp_Saldo]               MONEY         NULL,
    [Ack4_Antal_Saldo]                FLOAT (53)    NULL,
    [Ack4_Belopp_Saldo]               MONEY         NULL,
    [Ack5_Antal_Saldo]                FLOAT (53)    NULL,
    [Ack5_Belopp_Saldo]               MONEY         NULL,
    [User]                            VARCHAR (10)  NULL,
    [Uppdaterad]                      BIT           NULL,
    [Utskriven]                       BIT           NULL,
    [Sparr]                           BIT           NULL,
    [JournalNo]                       INT           NULL,
    [VerNo]                           INT           NULL,
    [VerSerie]                        VARCHAR (1)   NULL,
    [VerDatum]                        DATETIME      NULL,
    [ByEmail]                         BIT           NULL,
    [Exporterad]                      BIT           NULL,
    [Updated]                         DATETIME      NULL,
    [UpdatedBy]                       VARCHAR (10)  NULL,
    [TaxCount]                        BIT           NULL,
    [LoneNote]                        VARCHAR (MAX) NULL,
    [PreliminarSkatt_neg]             MONEY         NULL,
    [LonePeriodId]                    INT           NULL,
    [SemesterAr]                      INT           NULL,
    [Bankkonto]                       VARCHAR (20)  NULL,
    [Kalender]                        VARCHAR (MAX) NULL,
    [VäxaStöd]                        MONEY         NULL,
    [Karensavdrag]                    MONEY         NULL,
    [Semesterfaktor]                  MONEY         NULL,
    [PartlyUpdated]                   BIT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

