CREATE TABLE [dbo].[SkatteDeklaration] (
    [DeklarationsDag]     VARCHAR (10)  NOT NULL,
    [Period]              VARCHAR (15)  NULL,
    [PeriodMoms]          VARCHAR (25)  NULL,
    [MomsProc1]           FLOAT (53)    NULL,
    [MomsProc2]           FLOAT (53)    NULL,
    [MomsProc3]           FLOAT (53)    NULL,
    [Arbetsgivaravgift1]  FLOAT (53)    NULL,
    [Arbetsgivaravgift2]  FLOAT (53)    NULL,
    [SarskildLoneskatt]   FLOAT (53)    NULL,
    [ForetagsStod]        FLOAT (53)    NULL,
    [ForetagsStodMax]     MONEY         NULL,
    [5]                   MONEY         NULL,
    [6]                   MONEY         NULL,
    [7]                   MONEY         NULL,
    [8]                   MONEY         NULL,
    [10]                  MONEY         NULL,
    [11]                  MONEY         NULL,
    [12]                  MONEY         NULL,
    [13]                  MONEY         NULL,
    [14]                  MONEY         NULL,
    [15]                  MONEY         NULL,
    [20]                  MONEY         NULL,
    [21]                  MONEY         NULL,
    [22]                  MONEY         NULL,
    [23]                  MONEY         NULL,
    [24]                  MONEY         NULL,
    [25]                  MONEY         NULL,
    [26]                  MONEY         NULL,
    [30]                  MONEY         NULL,
    [31]                  MONEY         NULL,
    [32]                  MONEY         NULL,
    [33]                  MONEY         NULL,
    [34]                  MONEY         NULL,
    [35]                  MONEY         NULL,
    [36]                  MONEY         NULL,
    [37]                  MONEY         NULL,
    [38]                  MONEY         NULL,
    [39]                  MONEY         NULL,
    [40]                  MONEY         NULL,
    [41]                  MONEY         NULL,
    [42]                  MONEY         NULL,
    [43]                  MONEY         NULL,
    [SUFAA]               MONEY         NULL,
    [44]                  MONEY         NULL,
    [45]                  MONEY         NULL,
    [47]                  MONEY         NULL,
    [48]                  MONEY         NULL,
    [49]                  MONEY         NULL,
    [80]                  MONEY         NULL,
    [50]                  MONEY         NULL,
    [51]                  MONEY         NULL,
    [52]                  MONEY         NULL,
    [53]                  MONEY         NULL,
    [54]                  MONEY         NULL,
    [55]                  MONEY         NULL,
    [56]                  MONEY         NULL,
    [57]                  MONEY         NULL,
    [58]                  MONEY         NULL,
    [59]                  MONEY         NULL,
    [60]                  MONEY         NULL,
    [61]                  MONEY         NULL,
    [62]                  MONEY         NULL,
    [65]                  MONEY         NULL,
    [66]                  MONEY         NULL,
    [67]                  VARCHAR (2)   NULL,
    [68]                  MONEY         NULL,
    [69]                  MONEY         NULL,
    [70]                  MONEY         NULL,
    [73]                  MONEY         NULL,
    [74]                  MONEY         NULL,
    [75]                  MONEY         NULL,
    [76]                  MONEY         NULL,
    [77]                  MONEY         NULL,
    [78]                  MONEY         NULL,
    [81]                  MONEY         NULL,
    [82]                  MONEY         NULL,
    [83]                  MONEY         NULL,
    [84]                  MONEY         NULL,
    [85]                  MONEY         NULL,
    [86]                  MONEY         NULL,
    [87]                  MONEY         NULL,
    [88]                  MONEY         NULL,
    [90]                  MONEY         NULL,
    [99]                  MONEY         NULL,
    [Ftg_Moms]            MONEY         NULL,
    [Ftg_AGA]             MONEY         NULL,
    [Ftg_Prelskatt]       MONEY         NULL,
    [Ftg_F_SA]            MONEY         NULL,
    [Ftg_GetOrPay]        MONEY         NULL,
    [Ftg_Extrabetalning]  MONEY         NULL,
    [Underskrift]         VARCHAR (30)  NULL,
    [Telefon]             VARCHAR (20)  NULL,
    [SarskildLoneskatt_2] FLOAT (53)    NULL,
    [Ftg_Summa_AGA]       MONEY         NULL,
    [SLS_Born]            VARCHAR (30)  NULL,
    [Upplysn_Moms]        VARCHAR (MAX) NULL,
    [Upplysn_Ag]          VARCHAR (MAX) NULL,
    [Kontaktperson]       VARCHAR (30)  NULL,
    [ForetagsStod2]       FLOAT (53)    NULL,
    [ForetagsStodMax2]    MONEY         NULL,
    [Ftg_SSFAVG]          MONEY         NULL,
    [AlderPensAvgift]     FLOAT (53)    NULL,
    [Arbetsgivaravgift3]  FLOAT (53)    NULL,
    [Moms_klar]           BIT           NULL,
    [Ag_klar]             BIT           NULL,
    [MomsUlagImport]      MONEY         NULL,
    [MomsImportUtgHog]    MONEY         NULL,
    [MomsImportUtgMedel]  MONEY         NULL,
    [MomsImportUtgLag]    MONEY         NULL,
    PRIMARY KEY CLUSTERED ([DeklarationsDag] ASC)
);


GO

